Added Iteration model + some exception
TheCodexProject/The-Codex-Project-BackEndV2 pull request #11
Opened 2024-10-07 12:25 UTC by BjarkeBP

Model:
- Iteration
- IterationValidator

Exceptions:
- IterationTitleEmptyException
- IterationTitleTooLongException
- IterationTitleTooShortException

Also add spaces to UnitTests.csproj, idk why

2024-10-07 12:31 UTC, MalasataXD requested changes
"Minor" changes. A little of the same 😉

2024-10-07 12:31 UTC, MalasataXD commented on src/Tests/UnitTests/models/Iteration/IterationTests.cs
> +        Assert.NotEqual(Guid.Empty, iteration.Uid);
Remove... These are not necessary

2024-10-07 12:31 UTC, MalasataXD commented on src/Tests/UnitTests/models/Iteration/IterationTests.cs
> +    public void UpdateTitle_ShouldValidateCorrectly(string title, bool expectedFailure)
Split it up 👍

2024-10-07 12:31 UTC, MalasataXD commented on src/Tests/UnitTests/models/Iteration/IterationTests.cs
> +    [InlineData("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", false)]  // Valid title: max length
A little creativity?

2024-10-07 12:31 UTC, MalasataXD commented on src/core/domain/exceptions/models/Iteration/IterationTitle/IterationTitleEmptyException.cs
> +    protected IterationTitleEmptyException(SerializationInfo info, StreamingContext context) : base(info, context) { }
Remove.

2024-10-07 12:31 UTC, MalasataXD commented on src/core/domain/exceptions/models/Iteration/IterationTitle/IterationTitleEmptyException.cs
> +[Serializable]
Remove.

2024-10-07 12:31 UTC, MalasataXD commented on src/core/domain/exceptions/models/Iteration/IterationTitle/IterationTitleEmptyException.cs
> +﻿using System.Runtime.Serialization;
Remove

2024-10-07 12:31 UTC, MalasataXD commented on src/core/domain/exceptions/models/Iteration/IterationTitle/IterationTitleTooLongException.cs
> +    protected IterationTitleTooLongException(SerializationInfo info, StreamingContext context) : base(info, context) { }
Remove.

2024-10-07 12:31 UTC, MalasataXD commented on src/core/domain/exceptions/models/Iteration/IterationTitle/IterationTitleTooLongException.cs
> +[Serializable]
Remove

2024-10-07 12:31 UTC, MalasataXD commented on src/core/domain/exceptions/models/Iteration/IterationTitle/IterationTitleTooLongException.cs
> +﻿using System.Runtime.Serialization;
Remove

2024-10-07 12:31 UTC, MalasataXD commented on src/core/domain/exceptions/models/Iteration/IterationTitle/IterationTitleTooShortException.cs
> +    protected IterationTitleTooShortException(SerializationInfo info, StreamingContext context) : base(info, context) { }
Remove

2024-10-07 12:31 UTC, MalasataXD commented on src/core/domain/exceptions/models/Iteration/IterationTitle/IterationTitleTooShortException.cs
> +[Serializable]
Remove

2024-10-07 12:31 UTC, MalasataXD commented on src/core/domain/exceptions/models/Iteration/IterationTitle/IterationTitleTooShortException.cs
> +﻿using System.Runtime.Serialization;
Remove

2024-10-07 13:30 UTC, BjarkeBP commented on src/Tests/UnitTests/models/Iteration/IterationTests.cs
> +    [InlineData("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", false)]  // Valid title: max length
**NO**

2024-10-08 06:42 UTC, MalasataXD approved these changes
Nice work! It is ready to merge 👍

2024-10-08 10:33 UTC, merged