Organisation pull request
TheCodexProject/The-Codex-Project-BackEndV2 pull request #12
Opened 2024-10-07 13:14 UTC by Grey-rgb

Model:
- Organisation
- OrganisationValidator

Exceptions:
- OrganisationNameEmptyException
- OrganisationNameTooLongException
- OrganisationNameTooShortException
- OrganisationDocumentationAlreadyExistsException
- OrganisationDocumentationNotFoundException
- OrganisationNeedsAnOwnerException
- OrganisationOwnerAlreadyExistsException
- OrganisationOwnerNotFoundException

Tests:
- OrganisationTests

2024-10-07 13:37 UTC, MalasataXD requested changes
Minor changes. But you got it! 😉

2024-10-07 13:37 UTC, MalasataXD commented on src/core/domain/exceptions/models/Organisation/OrganisationDocumentationAlreadyExistsException.cs
> +    protected OrganisationDocumentationAlreadyExistsException(SerializationInfo info, StreamingContext context) : base(info, context) { }
Remove.

2024-10-07 13:37 UTC, MalasataXD commented on src/core/domain/exceptions/models/Organisation/OrganisationDocumentationAlreadyExistsException.cs
> +[Serializable]
Remove.

2024-10-07 13:37 UTC, MalasataXD commented on src/core/domain/exceptions/models/Organisation/OrganisationDocumentationAlreadyExistsException.cs
> +using System.Runtime.Serialization;
Remove.

2024-10-07 13:37 UTC, MalasataXD commented on src/core/domain/exceptions/models/Organisation/OrganisationDocumentationNotFoundException.cs
> +using System.Runtime.Serialization;
Remove.

2024-10-07 13:37 UTC, MalasataXD commented on src/core/domain/exceptions/models/Organisation/OrganisationDocumentationNotFoundException.cs
> +[Serializable]
Remove.

2024-10-07 13:37 UTC, MalasataXD commented on src/core/domain/exceptions/models/Organisation/OrganisationDocumentationNotFoundException.cs
> +    protected OrganisationDocumentationNotFoundException(SerializationInfo info, StreamingContext context) : base(info, context) { }
Remove.

2024-10-07 13:37 UTC, MalasataXD commented on src/core/domain/exceptions/models/Organisation/OrganisationName/OrganisationNameEmptyException.cs
> +using System.Runtime.Serialization;
Remove.

2024-10-07 13:37 UTC, MalasataXD commented on src/core/domain/exceptions/models/Organisation/OrganisationName/OrganisationNameEmptyException.cs
> +[Serializable]
Remove.

2024-10-07 13:37 UTC, MalasataXD commented on src/core/domain/exceptions/models/Organisation/OrganisationName/OrganisationNameEmptyException.cs
> +    protected OrganisationNameEmptyException(SerializationInfo info, StreamingContext context) : base(info, context) { }
Remove.

2024-10-07 13:37 UTC, MalasataXD commented on src/core/domain/exceptions/models/Organisation/OrganisationName/OrganisationNameTooLongException.cs
> +using System.Runtime.Serialization;
Remove.

2024-10-07 13:37 UTC, MalasataXD commented on src/core/domain/exceptions/models/Organisation/OrganisationName/OrganisationNameTooLongException.cs
> +[Serializable]
Remove.

2024-10-07 13:37 UTC, MalasataXD commented on src/core/domain/exceptions/models/Organisation/OrganisationName/OrganisationNameTooLongException.cs
> +    protected OrganisationNameTooLongException(SerializationInfo info, StreamingContext context) : base(info, context) { }
Remove.

2024-10-07 13:37 UTC, MalasataXD commented on src/core/domain/exceptions/models/Organisation/OrganisationName/OrganisationNameTooLongException.cs
> +    public OrganisationNameTooLongException(string message) : base(message) { }
Add documentation

2024-10-07 13:37 UTC, MalasataXD commented on src/core/domain/exceptions/models/Organisation/OrganisationName/OrganisationNameTooShortException.cs
> +    protected OrganisationNameTooShortException(SerializationInfo info, StreamingContext context) : base(info, context) { }
Remove.

2024-10-07 13:37 UTC, MalasataXD commented on src/core/domain/exceptions/models/Organisation/OrganisationName/OrganisationNameTooShortException.cs
> +using System.Runtime.Serialization;
Remove.

2024-10-07 13:37 UTC, MalasataXD commented on src/core/domain/exceptions/models/Organisation/OrganisationName/OrganisationNameTooShortException.cs
> +    public OrganisationNameTooShortException(string message) : base(message) { }
Add documentation

2024-10-07 13:37 UTC, MalasataXD commented on src/core/domain/exceptions/models/Organisation/OrganisationNeedsAnOwnerException.cs
> +    protected OrganisationNeedsAnOwnerException(SerializationInfo info, StreamingContext context) : base(info, context) { }
Remove.

2024-10-07 13:37 UTC, MalasataXD commented on src/core/domain/exceptions/models/Organisation/OrganisationNeedsAnOwnerException.cs
> +[Serializable]
Remove.

2024-10-07 13:37 UTC, MalasataXD commented on src/core/domain/exceptions/models/Organisation/OrganisationNeedsAnOwnerException.cs
> +using System.Runtime.Serialization;
Remove.

2024-10-07 13:37 UTC, MalasataXD commented on src/core/domain/exceptions/models/Organisation/OrganisationOwnerNotFoundException.cs
> +    protected OrganisationOwnerNotFoundException(SerializationInfo info, StreamingContext context) : base(info, context) { }
Remove.

2024-10-07 13:37 UTC, MalasataXD commented on src/core/domain/exceptions/models/Organisation/OrganisationOwnerNotFoundException.cs
> +[Serializable]
Remove.

2024-10-07 13:37 UTC, MalasataXD commented on src/core/domain/exceptions/models/Organisation/OrganisationOwnerNotFoundException.cs
> +using System.Runtime.Serialization;
Remove.

2024-10-07 13:37 UTC, MalasataXD commented on src/core/domain/exceptions/models/Organisation/OrganisationOwnerAlreadyExistsException.cs
> +using System.Runtime.Serialization;
Remove.

2024-10-07 13:37 UTC, MalasataXD commented on src/core/domain/exceptions/models/Organisation/OrganisationOwnerAlreadyExistsException.cs
> +[Serializable]
Remove.

2024-10-07 13:37 UTC, MalasataXD commented on src/core/domain/exceptions/models/Organisation/OrganisationOwnerAlreadyExistsException.cs
> +    protected OrganisationOwnerAlreadyExistsException(SerializationInfo info, StreamingContext context) : base(info, context) { }
Remove.

2024-10-08 06:43 UTC, MalasataXD requested changes
If you just fix my one little comment. It should be ready to merge 👍

2024-10-08 06:43 UTC, MalasataXD commented on src/Tests/UnitTests/models/Organisation/OrganisationTests.cs
> +    public class OrganisationTests
Just a minor thing.. It should actually be called `OrganisationModelTests` :wink

2024-10-08 11:17 UTC, MalasataXD approved these changes
LGTM 👍

2024-10-08 11:22 UTC, MalasataXD reviewed
LGTM 👍

2024-10-08 11:23 UTC, MalasataXD approved these changes
LGTM 🥇

2024-10-08 11:23 UTC, MalasataXD approved these changes
LETS GOO PLEASE :3

2024-10-08 11:24 UTC, BjarkeBP approved these changes
LGTM

2024-10-08 11:25 UTC, merged